variable "aws_region" {
  description = "AWS region for the private inference cell."
  type        = string
  default     = "us-east-1"
}

variable "availability_zone" {
  description = "Availability zone that offers the selected GPU instance."
  type        = string
  default     = "us-east-1b"
}

variable "environment" {
  description = "Short environment label used in names and tags."
  type        = string
  default     = "research"

  validation {
    condition     = can(regex("^[a-z][a-z0-9-]{1,20}$", var.environment))
    error_message = "environment must be a short lowercase identifier."
  }
}

variable "inference_enabled" {
  description = "Create the paid GPU instance only after the image and model are staged."
  type        = bool
  default     = false
}

variable "instance_type" {
  description = "Single-GPU instance for the first inference cell."
  type        = string
  default     = "g7e.2xlarge"
}

variable "ami_id" {
  description = "Pinned AWS Deep Learning Base OSS Nvidia Driver AMI ID."
  type        = string
  default     = ""

  validation {
    condition     = var.ami_id == "" || can(regex("^ami-[a-f0-9]+$", var.ami_id))
    error_message = "ami_id must be empty or a valid AMI ID."
  }
}

variable "root_volume_gib" {
  description = "Encrypted gp3 capacity for the OS, container layers, and staged model."
  type        = number
  default     = 300
}

variable "vllm_image_uri" {
  description = "Private ECR vLLM image URI pinned with @sha256:..."
  type        = string
  default     = ""

  validation {
    condition     = var.vllm_image_uri == "" || can(regex("@sha256:[a-f0-9]{64}$", var.vllm_image_uri))
    error_message = "vllm_image_uri must be empty or an immutable ECR digest."
  }
}

variable "model_repository" {
  description = "Auditable upstream model repository."
  type        = string
  default     = "Qwen/Qwen3.8-27B-FP8"
}

variable "model_revision" {
  description = "Exact upstream Qwen commit staged in the private model bucket."
  type        = string
  default     = "017b9c7af6b5689d5dd426a76e0bc077eb5ca20a"

  validation {
    condition     = can(regex("^[a-f0-9]{40}$", var.model_revision))
    error_message = "model_revision must be a full 40-character Git commit."
  }
}

variable "model_manifest_sha256" {
  description = "SHA-256 of model-manifest.sha256 generated by stage-model.sh."
  type        = string
  default     = ""

  validation {
    condition     = var.model_manifest_sha256 == "" || can(regex("^[a-f0-9]{64}$", var.model_manifest_sha256))
    error_message = "model_manifest_sha256 must be empty or a lowercase SHA-256 digest."
  }
}

variable "served_model_name" {
  description = "Stable model name exposed by the private OpenAI-compatible endpoint."
  type        = string
  default     = "amos-qwen38-27b-fp8"
}

variable "max_model_len" {
  description = "vLLM serving window on this GPU. Qwen 3.8-27B natively supports 262k; 65536 is the current Hosted product window on g7e.2xlarge."
  type        = number
  default     = 65536
}

variable "max_num_seqs" {
  description = "Concurrent logical worker sequences admitted by vLLM."
  type        = number
  default     = 8
}

variable "max_num_batched_tokens" {
  description = "Continuous-batching token budget. Keep this at least half of max_model_len so a 64k prompt is not crawled through 16k chunks."
  type        = number
  default     = 32768
}

variable "gpu_memory_utilization" {
  description = "vLLM GPU memory fraction; leaves headroom for warmup and MTP."
  type        = number
  default     = 0.85
}

variable "mtp_speculative_tokens" {
  description = "Native Qwen MTP draft tokens verified losslessly by the target model."
  type        = number
  default     = 3
}

variable "monthly_budget_usd" {
  description = "Optional AWS Budget threshold. Zero disables budget creation."
  type        = number
  default     = 0
}

variable "platform_vpc_id" {
  description = "AMOS platform ECS VPC to peer for Hosted Qwen. Empty skips peering."
  type        = string
  default     = ""

  validation {
    condition     = var.platform_vpc_id == "" || can(regex("^vpc-[a-f0-9]+$", var.platform_vpc_id))
    error_message = "platform_vpc_id must be empty or a vpc- id."
  }
}

variable "platform_vpc_cidr" {
  description = "CIDR of the platform VPC, used for the return route from the Qwen cell."
  type        = string
  default     = ""
}

variable "platform_route_table_ids" {
  description = "Platform private route tables that must reach the Qwen cell."
  type        = list(string)
  default     = []
}

variable "platform_ecs_security_group_id" {
  description = "ECS security group allowed to call vLLM and the Mission gateway. Empty skips both rules."
  type        = string
  default     = ""

  validation {
    condition     = var.platform_ecs_security_group_id == "" || can(regex("^sg-[a-f0-9]+$", var.platform_ecs_security_group_id))
    error_message = "platform_ecs_security_group_id must be empty or an sg- id."
  }
}

variable "swarm_gateway_enabled" {
  description = "Install the private Swarm Mission gateway through SSM. This never changes the vLLM service."
  type        = bool
  default     = false
}

variable "swarm_gateway_image_uri" {
  description = "Private ECR Swarm gateway image URI pinned with @sha256:..."
  type        = string
  default     = ""

  validation {
    condition     = var.swarm_gateway_image_uri == "" || can(regex("@sha256:[a-f0-9]{64}$", var.swarm_gateway_image_uri))
    error_message = "swarm_gateway_image_uri must be empty or an immutable ECR digest."
  }
}

variable "swarm_gateway_port" {
  description = "Private port exposed only to the Platform ECS security group."
  type        = number
  default     = 18081

  validation {
    condition     = var.swarm_gateway_port >= 1024 && var.swarm_gateway_port <= 65535 && var.swarm_gateway_port != 8000
    error_message = "swarm_gateway_port must be an unprivileged port distinct from vLLM port 8000."
  }
}

variable "swarm_gateway_backend_context_tokens" {
  description = "Context limit the gateway uses to budget private candidate and verifier evidence."
  type        = number
  default     = 65536

  validation {
    condition     = var.swarm_gateway_backend_context_tokens >= 4096 && var.swarm_gateway_backend_context_tokens <= 1048576
    error_message = "swarm_gateway_backend_context_tokens must be between 4096 and 1048576."
  }
}

variable "swarm_gateway_context_safety_tokens" {
  description = "Tokens reserved so private Swarm stages cannot overflow the shared Qwen context."
  type        = number
  default     = 1024

  validation {
    condition     = var.swarm_gateway_context_safety_tokens >= 128 && var.swarm_gateway_context_safety_tokens <= 131072
    error_message = "swarm_gateway_context_safety_tokens must be between 128 and 131072."
  }
}

variable "budget_email" {
  description = "Email notified at 50, 80, and 100 percent of the optional monthly budget."
  type        = string
  default     = ""

  validation {
    condition     = var.budget_email == "" || can(regex("^[^@\\s]+@[^@\\s]+\\.[^@\\s]+$", var.budget_email))
    error_message = "budget_email must be empty or a valid email address."
  }
}
